# Generated by Django 5.0.6 on 2026-01-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('inspection_due_date', models.DateField()),
                ('value_status', models.CharField(max_length=20)),
                ('current_model', models.CharField(max_length=50)),
                ('current_serial_number', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='visit_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='visits.visitrecord')),
            ],
        ),
    ]
