# Generated by Django 4.2 on 2026-01-12 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_customer_current_model_and_more'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrecord',
            name='current_model',
        ),
        migrations.RemoveField(
            model_name='visitrecord',
            name='current_serial_number',
        ),
        migrations.RemoveField(
            model_name='visitrecord',
            name='inspection_due_date',
        ),
        migrations.RemoveField(
            model_name='visitrecord',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='visitrecord',
            name='value_status',
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.ImageField(upload_to='visit_photos/', verbose_name='画像パス'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='status',
            field=models.CharField(choices=[('done', '完了'), ('absent', '不在'), ('retry', '再訪問')], max_length=20, verbose_name='訪問時ステータス'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='visit_date',
            field=models.DateTimeField(verbose_name='訪問日時'),
        ),
    ]
