# Generated by Django 4.2 on 2026-01-12 00:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_model',
            field=models.CharField(default=datetime.datetime(2026, 1, 12, 0, 53, 9, 421115, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='現取付型号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='current_serial_number',
            field=models.CharField(default=datetime.datetime(2026, 1, 12, 0, 53, 14, 266800, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='現社番'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='inspection_dur_date',
            field=models.DateField(blank=True, null=True, verbose_name='検定年月'),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reason',
            field=models.TextField(blank=True, verbose_name='事由'),
        ),
        migrations.AddField(
            model_name='customer',
            name='valv_status',
            field=models.CharField(default=datetime.datetime(2026, 1, 12, 0, 53, 16, 246456, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='開閉栓'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='丁目番地号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address3',
            field=models.CharField(blank=True, max_length=255, verbose_name='アパート名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='excess_category',
            field=models.CharField(max_length=50, verbose_name='超過分類'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='meter_location',
            field=models.CharField(max_length=255, verbose_name='メーター設置位置'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='お客様名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='usage_code',
            field=models.CharField(max_length=50, verbose_name='用途コード'),
        ),
    ]
